redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

redis_production: &redis
  adapter: redis
  url: redis://h:p87ff0a58c1ef1387d85388afeb583273bd995afaf704e2b177bc486345e24f8e@ec2-34-197-18-235.compute-1.amazonaws.com:18569

production: *redis_production
development: *redis
test: *redis
